name: Run Build
run-name: ${{ github.actor }} is running Build
on: [push]
jobs:
  testing-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
